debug: false
server:
  port: 3000
spring:
  datasource:
    url: ${SQL_URL}
    username: root
    password: ${SQL_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  sercurity:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${client-id-auth0}
            client-secret: ${client-secret-auth0}








