debug: true
server:
  port: 3000
  ssl:
    key-store: classpath:keystore/astreabackend.p12
    key-store-password: ""
    key-store-type: PKCS12
    key-alias: ${SSL_BACKEND}
    enabled: false
spring:
  datasource:
    url: ${SQL_URL}
    username: ${SQL_USER}
    password: ${SQL_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  sercurity:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${client-id-auth0}
            client-secret: ${client-secret-auth0}








